global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - backend-container:8080

  - job_name: 'prometheus'
    static_configs:
      - targets:
          - localhost:9090
